// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Zr17g_YAqdBMyTJgy537NVwhfjGksDg',
    appId: '1:1010777045063:web:2156eb7f11351aaa8c1962',
    messagingSenderId: '1010777045063',
    projectId: 'herrecord-adfd0',
    authDomain: 'herrecord-adfd0.firebaseapp.com',
    storageBucket: 'herrecord-adfd0.appspot.com',
    measurementId: 'G-Q7H07BFCLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYTjbB5QnDcYRLvTP3HgUAGi2ncoUeT_Q',
    appId: '1:1010777045063:android:236b58f25e0b4ad78c1962',
    messagingSenderId: '1010777045063',
    projectId: 'herrecord-adfd0',
    storageBucket: 'herrecord-adfd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_LAQW1r9fcmdb__krV69i6V3-1-LaAU',
    appId: '1:1010777045063:ios:ce70c02f61914e648c1962',
    messagingSenderId: '1010777045063',
    projectId: 'herrecord-adfd0',
    storageBucket: 'herrecord-adfd0.appspot.com',
    iosBundleId: 'com.example.herRecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-_LAQW1r9fcmdb__krV69i6V3-1-LaAU',
    appId: '1:1010777045063:ios:a87d16f35c04fa4a8c1962',
    messagingSenderId: '1010777045063',
    projectId: 'herrecord-adfd0',
    storageBucket: 'herrecord-adfd0.appspot.com',
    iosBundleId: 'com.example.herRecord.RunnerTests',
  );
}
